drop table mtp_dw_country CASCADE CONSTRAINTS;
drop table mtp_dw_region CASCADE CONSTRAINTS;
drop table mtp_dw_city CASCADE CONSTRAINTS;
drop table mtp_dw_patient CASCADE CONSTRAINTS;
drop table mtp_dw_time CASCADE CONSTRAINTS;
drop table mtp_dw_procedure CASCADE CONSTRAINTS;
drop table mtp_dw_facility CASCADE CONSTRAINTS;
drop table mtp_dw_appointment CASCADE CONSTRAINTS;
drop table mtp_dw_department_and_roles CASCADE CONSTRAINTS;